### ISSUE TITLE
Great tutorial, a small typo

### ISSUE THREAD

**Issue by kli-nlpr** [go2carter/nn-learn#1]
![qq 20170320105859](https://cloud.githubusercontent.com/assets/13194870/24087629/4b8bd7fe-0d5c-11e7-88cf-d5c751b6ff27.jpg)

sigmod->softmax

![qq 20170320111135](https://cloud.githubusercontent.com/assets/13194870/24087764/0363ae5a-0d5e-11e7-85fe-7bc3774aaf96.jpg)

brace should be deleted.

**Comment by go2carter** [comment]
Hi kli-nlpr, thanks for letting me know. Sigmoid and softmax are functionally the same, and taking the partial derivative of either should yield the same result. Will look back over my notes and change equation 10a appropriately. Thanks again!
