### ISSUE TITLE
Some confuse about the gradient of V

### ISSUE THREAD

**Issue by nbei** [go2carter/nn-learn#2]
Hi,
Thanks for your specification. However, I cannot understand why the gradient of V could be summarized by outer product. 
When we take gradient between scalar and Matrix, the result should be a matrix, right? But, if we use outer product, the final result will be a vector?
Maybe I am stupid on something, could you please clarify?

**Comment by go2carter** [comment]
Hi nbei,

No worries. The outer product of two vectors is a matrix.

I suggest looking at eq (13) in context of the definition found in the first paragraph here: https://en.wikipedia.org/wiki/Outer_product. Hopefully that helps.

**Comment by nbei** [comment]
Hi go2carter:

Thanks for your reply. 

I am so careless that I misunderstand the meaning of outer product and cross product. In china, we always use cross product and hardly did we mentioned outer product.

Thanks again for your clarification.

**Comment by go2carter** [comment]
No worries, nbei.

It may also be different fields. Physics problems frequently have outer products. Outer product is a specific example of the tensor product: https://en.wikipedia.org/wiki/Tensor_product
